# Generated by Django 5.2.17 on 2026-09-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        ('workspaces', '0002_workspaceinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('note', 'Note'), ('resource', 'Resource'), ('task', 'Task'), ('ticket', 'Ticket'), ('attachment', 'Attachment')], max_length=32)),
                ('object_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('search_text', models.TextField(blank=True)),
                ('tag_slugs', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to='tenancy.tenant')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'object_type'], name='search_sear_tenant__6a5219_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'object_type', 'object_id'), name='unique_search_document_object')],
            },
        ),
    ]
