#!/usr/bin/env python3
"""Extract the frontend tRPC call matrix.

Phase 2 Task P2-G (see docs/plans/cloud_surreal/02-feature-parity.md).

Reads every ``api.<router>.<procedure>`` (and ``streamApi.…``) usage in
``frontend/src`` and maps it to:

  - the Phase 2 slice that owns it, and
  - whether ``cloud_surreal`` already registers that procedure.

Emits:
  - cloud_surreal/route-matrix.json                    (machine-readable)
  - docs/plans/cloud_surreal/route-matrix.md           (human coverage matrix)

Run:  python3 cloud_surreal/scripts/extract_route_matrix.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
FRONTEND = REPO / "frontend" / "src"
APP = REPO / "cloud_surreal" / "app"
OUT_JSON = REPO / "cloud_surreal" / "route-matrix.json"
OUT_MD = REPO / "docs" / "plans" / "cloud_surreal" / "route-matrix.md"

# ``api.notes.list`` / ``streamApi.users.detail``. The lookbehind rejects domain
# names (``https://api.openai.com``) and member access that is not the client.
CALL_RE = re.compile(r"(?<![\w./$-])(?:api|streamApi)\.([A-Za-z_]\w*)\.([A-Za-z_]\w*)")
PROCEDURE_RE = re.compile(r"@router\.procedure\(\s*\"([^\"]+)\"\s*\)")

# Client router key (as mounted in server/routerTrpc/_app.ts) -> owning slice.
ROUTER_SLICE = {
    # S1 Identity
    "users": "S1",
    # S2 Notes core
    "notes": "S2",
    "tags": "S2",
    "comments": "S2",
    # S3 Planning
    "tickets": "S3",
    "study": "S3",
    "task": "S3",
    "planningFields": "S3",
    "planningCategories": "S3",
    "planningLinks": "S3",
    # S4 Files
    "attachments": "S4",
    # S5 Analytics and config
    "analytics": "S5",
    "config": "S5",
    "branding": "S5",
    "fonts": "S5",
    "notifications": "S5",
    "public": "S5",
    # S6 Collaboration
    "follows": "S6",
    "shareApprovals": "S6",
    "conversation": "S6",
    "message": "S6",
    "agentDirectories": "S6",
    # S7 Integrations
    "plugin": "S7",
    "mcpServers": "S7",
    "skills": "S7",
    # S8 AI
    "ai": "S8",
    "aiTask": "S8",
}


def _frontend_files() -> list[Path]:
    return sorted(
        path
        for path in FRONTEND.rglob("*")
        if path.suffix in (".ts", ".tsx") and path.is_file()
    )


def extract_calls() -> dict[str, dict]:
    calls: dict[str, dict] = {}
    for path in _frontend_files():
        text = path.read_text(encoding="utf-8", errors="ignore")
        for match in CALL_RE.finditer(text):
            symbol = f"{match.group(1)}.{match.group(2)}"
            entry = calls.setdefault(symbol, {"calls": 0, "files": set()})
            entry["calls"] += 1
            entry["files"].add(str(path.relative_to(FRONTEND)))
    return calls


def implemented_procedures() -> set[str]:
    names: set[str] = set()
    for path in sorted(APP.rglob("*.py")):
        text = path.read_text(encoding="utf-8", errors="ignore")
        names.update(PROCEDURE_RE.findall(text))
    return names


def owning_slice(symbol: str) -> str:
    router = symbol.split(".", 1)[0]
    return ROUTER_SLICE.get(router, "UNMAPPED")


def build_matrix() -> dict:
    calls = extract_calls()
    implemented = implemented_procedures()
    symbols = {}
    for symbol, data in sorted(calls.items()):
        slice_ = owning_slice(symbol)
        symbols[symbol] = {
            "calls": data["calls"],
            "files": sorted(data["files"]),
            "owningSlice": slice_,
            "implemented": symbol in implemented,
        }
    return {
        "generatedFrom": "frontend/src (**/*.ts, **/*.tsx)",
        "patterns": ["api.<router>.<procedure>", "streamApi.<router>.<procedure>"],
        "implementedProcedures": sorted(implemented),
        "symbols": symbols,
    }


def _markdown(payload: dict) -> str:
    symbols = payload["symbols"]
    unmapped = [
        name for name, data in symbols.items() if data["owningSlice"] == "UNMAPPED"
    ]
    implemented = sum(1 for data in symbols.values() if data["implemented"])

    lines = [
        "# cloud_surreal Frontend Route Matrix (Phase 2 Task P2-G)",
        "",
        "> Generated by `cloud_surreal/scripts/extract_route_matrix.py`. Do not",
        "> hand-edit; re-run the script. `Status` is `done` when `cloud_surreal`",
        "> registers the procedure, else `pending` (owned by the slice in the row).",
        "",
        f"**Source:** `{payload['generatedFrom']}`.",
        f"**Symbols:** {len(symbols)}. **Implemented:** {implemented}.",
        f"**Unmapped:** {len(unmapped)}.",
        "",
        "## Coverage matrix",
        "",
        "| symbol | calls | owning slice | status |",
        "| --- | --- | --- | --- |",
    ]
    for name, data in symbols.items():
        status = "done" if data["implemented"] else "pending"
        lines.append(
            f"| `{name}` | {data['calls']} | {data['owningSlice']} | {status} |"
        )

    lines += [
        "",
        "## Slice summary",
        "",
        "| slice | symbols | done |",
        "| --- | --- | --- |",
    ]
    slices = sorted({data["owningSlice"] for data in symbols.values()})
    for slice_ in slices:
        members = [d for d in symbols.values() if d["owningSlice"] == slice_]
        done = sum(1 for d in members if d["implemented"])
        lines.append(f"| {slice_} | {len(members)} | {done} |")

    lines += ["", "## Unmapped symbols", ""]
    if unmapped:
        lines.extend(
            f"- `{name}` — add its router to `ROUTER_SLICE` in the extractor."
            for name in unmapped
        )
    else:
        lines.append("- none")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    payload = build_matrix()
    OUT_JSON.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    OUT_MD.write_text(_markdown(payload), encoding="utf-8")

    symbols = payload["symbols"]
    unmapped = [
        name for name, data in symbols.items() if data["owningSlice"] == "UNMAPPED"
    ]
    done = sum(1 for data in symbols.values() if data["implemented"])
    print(f"wrote {OUT_JSON.relative_to(REPO)} ({len(symbols)} symbols)")
    print(
        f"wrote {OUT_MD.relative_to(REPO)} "
        f"(implemented: {done}, unmapped: {len(unmapped)})"
    )


if __name__ == "__main__":
    main()
