"""Superuser bootstrap (slice S1d).

Port of ``bootstrapSuperuserFromEnv`` in ``server/index.ts``. Without this a
``cloud_surreal`` deployment has no way to create the first account, which blocks
the Phase 5 cutover entirely.

The four branches are preserved exactly:

1. **env username + password (12+ chars)** — upsert that account as ``superadmin``
   with a re-hashed password. The credential note is only written the first time
   (no superadmin *and* no account with that name already existed).
2. **env username + password shorter than 12 chars** — warn and skip; a bad
   env var must not silently produce an unusable admin.
3. **no env, no superadmin yet** — generate a shell-safe 32-char password for
   ``PLANINC_SUPERUSER_NAME || "admin"``, create the account, and write the
   credential note.
4. **no env, superadmin already exists** — do nothing, leaving the existing
   password alone (so removing the env var is not a lockout).

Failures are logged, never fatal: a bootstrap problem must not stop the server
from listening, matching the TS ``try/catch``.

The generated alphabet is letters+digits only. The Makefile sources ``.env`` with
``set -a``, so a password containing shell metacharacters would corrupt the
environment — the same constraint the TS generator and
``docs/06-secrets-and-superuser.md`` describe.
"""

from __future__ import annotations

import os
import secrets
import string
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .passwords import hash_password

DEFAULT_USERNAME = "admin"
MIN_PASSWORD_LENGTH = 12
PASSWORD_ALPHABET = string.ascii_letters + string.digits
SUPERUSER_FILE = "superuser.txt"

# Fields the TS bootstrap carries over from an existing account so a password
# rotation does not wipe the avatar, tokens, or links.
PRESERVED_FIELDS = ("image", "apiToken", "note", "description", "linkAccountId")


@dataclass(frozen=True)
class BootstrapResult:
    """What the bootstrap did, so callers and tests can assert on it."""

    action: str  # created | updated | generated | unchanged | skipped | failed
    username: str = ""
    account_id: int | None = None
    reason: str = ""
    wrote_credentials: bool = False
    generated_password: str | None = None


def generate_shell_safe_password(length: int = 32) -> str:
    """``generateShellSafePassword``: uniform letters/digits, shell-safe."""
    return "".join(secrets.choice(PASSWORD_ALPHABET) for _ in range(length))


def resolve_credentials_path(db_file: str) -> Path:
    """``resolveSuperuserTxtPath``: ``superuser.txt`` beside the database file."""
    resolved = Path(db_file).expanduser()
    directory = resolved.parent if resolved.parent != Path("") else Path.cwd()
    return directory / SUPERUSER_FILE


def write_credentials(
    path: Path, username: str, password: str, generated: bool
) -> bool:
    """Write the credential note at ``0600``; returns whether it was written."""
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            "# PlanInc superuser — created on first boot",
            f"# Generated by cloud_surreal (generated: {'yes' if generated else 'no'})",
            f"username: {username}",
            f"password: {password}",
            "",
            "Sign in at http://localhost:1111/signin or https://notes.structa.cloud/signin",
            "Save this password in a manager, then delete this file.",
            "This file is gitignored and chmod 0600.",
            "",
        ]
        # Create with the restrictive mode up front so the secret is never briefly
        # world-readable, then re-apply for filesystems that ignore the mode.
        handle = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(handle, "w", encoding="utf-8") as stream:
            stream.write("\n".join(lines))
        try:
            os.chmod(path, 0o600)
        except OSError:
            pass
        return True
    except OSError:
        return False


async def bootstrap_superuser(
    service: Any,
    settings: Any,
    log: Any = None,
) -> BootstrapResult:
    """Apply the four bootstrap branches. Never raises."""
    emit = log if log is not None else (lambda message: None)
    env_username = str(getattr(settings, "superuser_name", "") or "").strip()
    env_password = str(getattr(settings, "superuser_password", "") or "").strip()
    credentials_path = resolve_credentials_path(settings.db_file)

    try:
        existing_named = await service.by_name(env_username) if env_username else None
        existing_superadmin = await service.first_where(role="superadmin")

        if env_username and env_password:
            if len(env_password) < MIN_PASSWORD_LENGTH:
                emit(
                    "[superuser] PLANINC_SUPERUSER_PASSWORD must be at least "
                    f"{MIN_PASSWORD_LENGTH} characters; skipping"
                )
                return BootstrapResult(
                    action="skipped",
                    username=env_username,
                    reason="password too short",
                )
            data = {
                "name": env_username,
                "nickname": env_username,
                "password": hash_password(env_password),
                "role": "superadmin",
                "loginType": "",
            }
            if existing_named is not None:
                for key in PRESERVED_FIELDS:
                    data[key] = existing_named.get(key)
                updated = await service.update(existing_named["id"], data)
                emit(
                    f'[superuser] Updated superuser "{env_username}" from '
                    f"environment (id {updated.get('id')})."
                )
                result = BootstrapResult(
                    action="updated",
                    username=env_username,
                    account_id=_as_int(updated.get("id")),
                )
            else:
                created = await service.create(
                    name=env_username, password=env_password, role="superadmin"
                )
                emit(
                    f'[superuser] Bootstrapped superuser "{env_username}" from '
                    f"environment (id {created.get('id')})."
                )
                result = BootstrapResult(
                    action="created",
                    username=env_username,
                    account_id=_as_int(created.get("id")),
                )

            # First boot only: leave a local credential note next to the DB file.
            if existing_superadmin is None and existing_named is None:
                wrote = write_credentials(
                    credentials_path, env_username, env_password, generated=False
                )
                return _with_credentials(result, wrote)
            return result

        if existing_superadmin is not None:
            return BootstrapResult(action="unchanged", username=env_username)

        username = env_username or DEFAULT_USERNAME
        secret = generate_shell_safe_password(32)
        created = await service.create(
            name=username, password=secret, role="superadmin"
        )
        emit(
            f'[superuser] Bootstrapped superuser "{username}" with generated '
            f"password (id {created.get('id')})."
        )
        wrote = write_credentials(credentials_path, username, secret, generated=True)
        return BootstrapResult(
            action="generated",
            username=username,
            account_id=_as_int(created.get("id")),
            wrote_credentials=wrote,
            generated_password=secret if not wrote else None,
        )
    except Exception as err:  # noqa: BLE001 - a bootstrap failure must not block boot
        emit(f"[superuser] env bootstrap failed: {err}")
        return BootstrapResult(action="failed", username=env_username, reason=str(err))


def _with_credentials(result: BootstrapResult, wrote: bool) -> BootstrapResult:
    return BootstrapResult(
        action=result.action,
        username=result.username,
        account_id=result.account_id,
        reason=result.reason,
        wrote_credentials=wrote,
    )


def _as_int(value: Any) -> int | None:
    try:
        return int(str(value).rsplit(":", 1)[-1])
    except (TypeError, ValueError):
        return None
