# Generated by Django 5.2.17 on 2026-09-27 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0004_note_workspace_notecomment_tag_note_tags_notelink_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('workspace', 'Workspace')], default='public', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='notes.note')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('events', models.JSONField(blank=True, default=list)),
                ('encrypted_secret', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhookendpoint')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('transport', models.CharField(choices=[('sse', 'SSE'), ('stdio', 'stdio'), ('http', 'HTTP')], default='sse', max_length=16)),
                ('encrypted_api_key', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_servers', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='unique_mcp_server_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='PluginInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_installations', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='unique_plugin_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_feeds', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'url'), name='unique_rss_feed_url_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='SSOConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('oidc', 'OIDC'), ('saml', 'SAML'), ('github', 'GitHub'), ('google', 'Google')], max_length=32)),
                ('metadata_url', models.URLField(blank=True, max_length=1000)),
                ('client_id', models.CharField(blank=True, max_length=300)),
                ('encrypted_client_secret', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_connections', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['provider', 'id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'provider'), name='unique_sso_connection_per_tenant')],
            },
        ),
        migrations.AddConstraint(
            model_name='webhookendpoint',
            constraint=models.UniqueConstraint(fields=('tenant', 'url'), name='unique_webhook_url_per_tenant'),
        ),
    ]
