# Generated by Django 5.2.17 on 2026-09-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outboxevent',
            new_name='operations__publish_920a41_idx',
            old_name='operations__publish_5c43f9_idx',
        ),
        migrations.RenameIndex(
            model_name='outboxevent',
            new_name='operations__tenant__42f260_idx',
            old_name='operations__tenant_i_1d5f86_idx',
        ),
    ]
