# Generated by Django 5.2.17 on 2026-09-27 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_rename_operations__publish_5c43f9_idx_operations__publish_920a41_idx_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=120)),
                ('scope', models.CharField(blank=True, default='', max_length=180)),
                ('cursor', models.JSONField(blank=True, default=dict)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_checkpoints', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'job_type'], name='operations__tenant__08ad8b_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'job_type', 'scope'), name='operations_jobcheckpoint_unique_scope')],
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_type', models.CharField(max_length=80)),
                ('ttl_days', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policies', to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'aggregate_type'), name='operations_retentionpolicy_unique_type')],
            },
        ),
        migrations.CreateModel(
            name='RetentionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.CharField(max_length=120)),
                ('action', models.CharField(choices=[('purged', 'purged'), ('retained', 'retained')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_records', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'aggregate_type', 'created_at'], name='operations__tenant__1ec37a_idx')],
            },
        ),
    ]
