# Generated by Django 5.2.17 on 2026-09-27 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=120)),
                ('period_start', models.DateField()),
                ('value', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-period_start', 'metric'],
                'indexes': [models.Index(fields=['tenant', 'period_start'], name='analytics_m_tenant__c8d9be_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'metric', 'period_start'), name='unique_metric_snapshot')],
            },
        ),
    ]
