#!/usr/bin/env python3
"""Generate per-directory README.md files for PlanInc.

Follows the documentation standard established in `django-fusion`: every project
directory carries a `README.md` describing its role, its contents and its public
API. Content is **derived from the code**, not stubbed:

  * the description is taken from the module doc-comment of the directory's entry
    file when one exists, otherwise from the directory's classified role;
  * `## Contents` is a real inventory of the directory, each source file
    annotated with the first line of its own doc comment;
  * `## Public API` is parsed from the entry file's `export` statements.

Hand-written READMEs are never overwritten. A file is only replaced when it
carries the generator footer in `GENERATOR_MARKER`.

Usage:
    python3 scripts/generate-dir-docs.py            # write/refresh READMEs
    python3 scripts/generate-dir-docs.py --check    # exit 1 if any dir lacks one
    python3 scripts/generate-dir-docs.py --dry-run  # show what would change
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

# --------------------------------------------------------------------------- #
# Project identity
# --------------------------------------------------------------------------- #

PROJECT = "PlanInc"
TAGLINE = "AI-powered card note-taking and planning"
GENERATOR_MARKER = "Auto-generated by `scripts/generate-dir-docs.py`"
REL_GENERATOR = "scripts/generate-dir-docs.py"

# Directories never documented: dependencies, build output and runtime state.
EXCLUDE_DIRS = {
    ".git",
    ".github-workflows-cache",
    "node_modules",
    "__pycache__",
    ".pytest_cache",
    ".turbo",
    ".cache",
    ".venv",
    "venv",
    "coverage",
    ".nyc_output",
    "dist",
    "build",
    ".next",
    "test-results",
    "playwright-report",
    "data",
}

SOURCE_EXT = {".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".py", ".sh", ".rs"}
LOCALE_EXT = {".json", ".js", ".mjs", ".ts"}

# --------------------------------------------------------------------------- #
# Hand-authored purposes for the structural directories.
# Leaf directories are described automatically from their contents.
# --------------------------------------------------------------------------- #

PURPOSE: dict[str, str] = {
    ".": (
        "Repository root. Holds the deployable `runtime/` application, the "
        "upstream `src/` monorepo it was extracted from, and the compose/Make "
        "tooling that puts it on the edge as `notes.structa.cloud`."
    ),
    "runtime": (
        "The canonical deployed application: a dependency-light Node HTTP server "
        "(`server.mjs`) that serves the PlanInc UI and API on top of an embedded "
        "SurrealDB (`surrealkv://`) store. This is what the `planinc` container runs."
    ),
    "runtime/public": (
        "Static front-end served by `server.mjs`. Vanilla ES modules - no build "
        "step - so the runtime image stays small and boots without a bundler."
    ),
    "runtime/public/vendor": (
        "Third-party browser libraries vendored verbatim. Do not hand-edit; "
        "update by replacing the file and noting the upstream version."
    ),
    "runtime/context": (
        "Drop-in context workspace consumed by the runtime's agent/context "
        "features. Kept empty in git; populated per deployment."
    ),
    "runtime/tests": (
        "Playwright integration suite. Specs drive the real server over HTTP, so "
        "they assert behaviour rather than mocks."
    ),
    "runtime/tests/fixtures": (
        "Binary fixtures (images, PDFs) uploaded by the specs to exercise the "
        "attachment pipeline."
    ),
    "docs": (
        "Long-form documentation, indexed by [`INDEX.md`](./INDEX.md). Start "
        "there for the documentation map (`PI-NNN` IDs). The pages here are "
        "hand-written; the per-directory `README.md` files are generated."
    ),
    "scripts": (
        "Development tooling. `generate-dir-docs.py` produces and enforces the "
        "per-directory READMEs described in [`docs/INDEX.md`](../docs/INDEX.md)."
    ),
    "src": (
        "Upstream PlanInc monorepo (Bun workspaces: `app`, `server`, `shared`). "
        "Retained as the source of truth for feature work; the deployed artifact "
        "is `runtime/`."
    ),
    "src/app": (
        "Desktop/web client. React + Vite, shipped both as a web bundle and as a "
        "Tauri desktop app."
    ),
    "frontend/public": "Static assets copied verbatim into the Vite build.",
    "frontend/src": "Client source tree.",
    "frontend/src/assets": "Bundled static assets imported by components.",
    "frontend/src/components": (
        "React component library. Grouped as `Common/` (reusable primitives), "
        "`Layout/`, and feature components named `Planinc*`."
    ),
    "frontend/src/hooks": "Reusable React hooks.",
    "frontend/src/lib": "Client-side library code: API clients, storage, i18n and helpers.",
    "frontend/src/pages": "Route-level page components.",
    "frontend/src/store": (
        "State management, built on a custom store base with per-domain stores "
        "plus pluggable `module/` and `standard/` primitives."
    ),
    "frontend/src/styles": "Global stylesheets and vendor style overrides.",
    "frontend/src-tauri": (
        "Tauri desktop shell: Rust host, capabilities and per-platform generated "
        "projects."
    ),
    "frontend/tauri-plugin-planinc": "Tauri plugin exposing native PlanInc capabilities to the web layer.",
    "src/helm": "Helm chart for Kubernetes deployment of PlanInc.",
    "planinc-types": "Published type package consumed by the client and server.",
    "server": (
        "Backend: Express + tRPC API, AI provider abstraction and background jobs."
    ),
    "server/aiServer": "AI layer - model factory, providers, tools and MCP bridge.",
    "server/aiServer/mcp": "Model Context Protocol client manager and tool bridge.",
    "server/aiServer/providers": (
        "Provider abstraction (LLM, embedding, audio) over the AI SDK."
    ),
    "server/aiServer/tools": "Agent tools exposed to the model (create/search/update notes, web).",
    "server/jobs": "Scheduled and queue-driven background jobs.",
    "server/lib": "Server utilities - storage, queues, scheduling and integration clients.",
    "server/middleware": "Express middleware (auth context, error handling).",
    "server/routerExpress": "REST routes: auth, files, MCP, OpenAI-compatible API and RSS.",
    "server/routerTrpc": "tRPC router - the primary typed API surface.",
    "server/scripts": "One-off operational scripts (superuser creation, fixture seeding).",
    "server/seedfiles": "Seed media shipped with the database seeder.",
    "server/types": "Ambient type augmentations for Express and tRPC.",
    "server/vditor": "Vendored Vditor editor bundle and its diagram/render libraries.",
    "shared": "Code shared by client and server (Bun workspace `@planinc/shared`).",
    "shared/lib/__tests__": (
        "Unit tests for the shared isomorphic helpers. Run with `turbo run test` "
        "from `src/`."
    ),
    ".github": "GitHub community-health files, issue templates and CI workflows.",
    ".github/workflows": "CI workflow definitions (build, test, release).",
    ".github/ISSUE_TEMPLATE": "Issue report templates.",
    ".github/changelog": "Changelog fragments consumed by the release workflow.",
    "frontend/src/lib/utils": "Small focused utility modules shared across the client.",
    "frontend/src/store/module": (
        "Reusable state modules: `Dialog`, `DialogStandalone` and `Toast` providers "
        "plus the app-level `AppProvider`."
    ),
    "frontend/src/store/module/Dialog": "Modal dialog state module.",
    "frontend/src/store/module/DialogStandalone": (
        "Imperative dialogs rendered outside the React tree."
    ),
    "frontend/src/store/module/Toast": "Toast notification state module.",
    "frontend/src/store/standard": (
        "Store primitives: `base`, promise/async state, object pooling and "
        "persisted list state that the per-domain stores build on."
    ),
    "frontend/src/store/plugin": (
        "Plugin runtime: registry, manager, render pipeline and the API surface "
        "exposed to plugins."
    ),
    "frontend/src/components/Common": (
        "Reusable UI primitives shared across features - editors, markdown "
        "rendering, dialogs, pickers and layout helpers."
    ),
    "frontend/src-tauri/capabilities": (
        "Tauri v2 capability grants: which native commands the web layer may call."
    ),
    "frontend/src-tauri/src": "Rust host for the Tauri desktop shell.",
    "frontend/src-tauri/src/desktop": "Desktop-specific Rust commands and window wiring.",
    "src/test-docker/mock-openai": (
        "Mock OpenAI-compatible endpoint used by containerised tests to exercise "
        "AI paths without spending quota."
    ),
    "shared/lib": "Isomorphic helpers: cache, dates, lodash subset, schemas and constants.",
    "src/test-docker": "Containerised test fixtures - a mock OpenAI endpoint and its compose file.",
    "src/helm/templates": "Kubernetes manifests rendered by the chart.",
    "src/helm/charts": "Chart dependencies.",
}

# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #


def humanize(name: str) -> str:
    """`AIWriteButton` -> `AI Write Button`; `s3file` -> `s3file`."""
    if not name:
        return name
    if name.isupper():
        return name
    spaced = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", name)
    spaced = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", " ", spaced)
    return spaced.replace("_", " ").replace("-", " ").strip()


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def doc_comment(path: Path) -> str:
    """First meaningful line of a file's leading doc comment or docstring."""
    text = read_text(path)
    if not text:
        return ""

    if path.suffix in {".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"}:
        block = re.match(r"\s*/\*\*(.*?)\*/", text, re.S)
        if block:
            for line in block.group(1).splitlines():
                line = line.strip().lstrip("*").strip()
                if line and not line.startswith("@"):
                    return line
        for line in text.splitlines()[:12]:
            stripped = line.strip()
            if stripped.startswith("//"):
                body = stripped.lstrip("/").strip()
                if body and not body.startswith(("@", "-", "=")):
                    return body
            elif stripped and not stripped.startswith(("import", "/*")):
                break

    if path.suffix == ".py":
        match = re.match(r'\s*(?:#[^\n]*\n)*\s*(?:"""|\'\'\')(.*?)(?:"""|\'\'\')', text, re.S)
        if match:
            for line in match.group(1).splitlines():
                line = line.strip()
                if line:
                    return line

    if path.suffix == ".sh":
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("#!"):
                continue
            if stripped.startswith("#"):
                body = stripped.lstrip("#").strip()
                if body:
                    return body
            elif stripped:
                break

    if path.suffix in {".yml", ".yaml"}:
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("#"):
                body = stripped.lstrip("#").strip()
                if body:
                    return body
            elif stripped:
                break

    return ""


def classify(rel: str, path: Path) -> str:
    parts = [p for p in rel.split("/") if p and p != "."]
    joined = "/".join(parts)

    if "locales" in parts:
        return "locale"
    if any(p in {"vendor", "vditor"} for p in parts):
        return "vendored"
    if "gen" in parts or any(p.endswith("-gen") for p in parts):
        return "generated"
    if "res" in parts or "icons" in parts:
        return "assets"
    if parts and parts[0] == "src" and "helm" in parts:
        return "infra"
    if "configs" in parts or joined.startswith("configs"):
        return "config"
    if any(p in {"charts", "templates"} for p in parts):
        return "infra"
    return "source"


def entry_file(path: Path) -> Path | None:
    for name in (
        "index.ts",
        "index.tsx",
        "index.js",
        "index.mjs",
        "index.jsx",
        "mod.rs",
        "__init__.py",
    ):
        candidate = path / name
        if candidate.is_file():
            return candidate
    return None


EXPORT_RE = re.compile(
    r"^\s*export\s+(?:default\s+)?(?:async\s+)?"
    r"(?:const|let|var|function|class|interface|type|enum|abstract\s+class)\s+"
    r"([A-Za-z_$][\w$]*)",
    re.M,
)
EXPORT_LIST_RE = re.compile(r"^\s*export\s*\{([^}]*)\}", re.M | re.S)
PY_DEF_RE = re.compile(r"^(?:def|class)\s+([A-Za-z_]\w*)", re.M)


def public_api(path: Path, kind: str) -> tuple[list[str], str]:
    """Return (symbols, header). Header is `Public API` or `Modules`."""
    entry = entry_file(path)
    if kind in {"source", "config"} and entry is not None:
        text = read_text(entry)
        if entry.suffix == ".py":
            symbols = PY_DEF_RE.findall(text)
        else:
            symbols = EXPORT_RE.findall(text)
            for group in EXPORT_LIST_RE.findall(text):
                for chunk in group.split(","):
                    chunk = chunk.strip()
                    if not chunk:
                        continue
                    if " as " in chunk:
                        chunk = chunk.split(" as ")[-1].strip()
                    if re.fullmatch(r"[A-Za-z_$][\w$]*", chunk):
                        symbols.append(chunk)
        seen: list[str] = []
        for sym in symbols:
            if sym not in seen:
                seen.append(sym)
        if seen:
            return seen, "Public API"

    return [], "Public API"


def describe(rel: str, path: Path, kind: str) -> str:
    if rel in PURPOSE:
        return PURPOSE[rel]

    name = path.name
    if kind == "locale":
        return (
            f"Translation bundle for the `{name}` locale. Keys are looked up by "
            "the runtime i18n layer; `en` is the reference set."
        )
    if kind == "vendored":
        return (
            f"Vendored third-party code for `{name}`. Do not hand-edit - replace "
            "wholesale when upgrading upstream."
        )
    if kind == "generated":
        return (
            f"Generated output for `{name}`. Produced by its toolchain; edits here "
            "are overwritten on regeneration."
        )
    if kind == "assets":
        return f"Static resources for `{name}`."
    if kind == "infra":
        return f"Infrastructure definitions under `{rel}/`."

    entry = entry_file(path)
    if entry is not None:
        summary = doc_comment(entry)
        if summary:
            return summary

    try:
        entries = sorted(p for p in path.iterdir() if p.name not in EXCLUDE_DIRS)
    except OSError:
        entries = []
    subdirs = [p.name for p in entries if p.is_dir()]
    sources = [p.name for p in entries if p.is_file() and p.suffix in SOURCE_EXT]

    if subdirs:
        listed = ", ".join(f"`{d}`" for d in subdirs[:8])
        if len(subdirs) > 8:
            listed += f", and {len(subdirs) - 8} more"
        tail = (
            f" It also holds {len(sources)} top-level modules."
            if sources
            else ""
        )
        return (
            f"Groups {len(subdirs)} sub-area"
            f"{'s' if len(subdirs) != 1 else ''}: {listed}.{tail}"
        )

    if sources:
        listed = ", ".join(f"`{s}`" for s in sources[:6])
        if len(sources) > 6:
            listed += f", and {len(sources) - 6} more"
        return f"Modules: {listed}."

    return f"`{humanize(name)}` - resource directory; see the inventory below."


def usage_block(rel: str, kind: str, symbols: list[str]) -> str:
    if kind == "locale":
        return (
            "```ts\n"
            'import i18n from "@/lib/i18n";   // frontend/src/lib/i18n.ts\n\n'
            f'i18n.t("some.key", {{ lng: "{rel.split("/")[-1]}" }});\n'
            "```"
        )
    if kind in {"vendored", "generated", "assets"}:
        return (
            "Nothing here is imported directly by project code; it is consumed by "
            "the toolchain or reference only."
        )
    if rel.startswith("runtime"):
        return (
            "```bash\n"
            "cd runtime && npm test          # drive the runtime through Playwright\n"
            "```"
        )
    if rel.startswith("server"):
        return (
            "```ts\n"
            f'// from {rel}\n'
            'import { ... } from "@planinc/backend";\n'
            "```"
        )
    if rel.startswith("shared") and not rel.endswith("index.ts"):
        tail = rel[len("shared") :].strip("/")
        spec = f"@planinc/shared/{tail}" if tail else "@planinc/shared"
        return (
            "```ts\n"
            f'// from {rel}\n'
            f'import {{ ... }} from "{spec}";\n'
            "```"
        )
    if rel.startswith("src/app"):
        return (
            "```ts\n"
            f'// from {rel}\n'
            'import { ... } from "@planinc/frontend";\n'
            "```"
        )
    if kind == "config":
        return (
            "```bash\n"
            "make validate   # from the proxy repo root\n"
            "```"
        )
    if symbols:
        first = symbols[0]
        return (
            "```ts\n"
            f"// from {rel}\n"
            f'import {{ {first} }} from "./{entry_name(rel)}";\n'
            "```"
        )
    return "No public entry point; import the individual modules directly."


def entry_name(rel: str) -> str:
    return "index"


def contents_block(rel: str, path: Path, kind: str) -> str:
    try:
        entries = sorted(path.iterdir(), key=lambda p: (p.is_file(), p.name.lower()))
    except OSError:
        return "_(unreadable)_"

    lines: list[str] = []
    shown = 0
    for item in entries:
        if item.name in EXCLUDE_DIRS or item.name.startswith(".git"):
            continue
        if item.name == "README.md":
            continue
        if shown >= 40:
            lines.append(f"- _...and {len(entries) - shown} more entries_")
            break
        shown += 1
        if item.is_dir():
            count = sum(
                1
                for _ in item.rglob("*")
                if _.is_file()
                and _.name != "README.md"
                and not any(part in EXCLUDE_DIRS for part in _.relative_to(path).parts)
            )
            lines.append(f"- `{item.name}/` - {count} file{'s' if count != 1 else ''}")
        else:
            if kind in {"locale", "assets", "vendored"} and item.suffix in {".png", ".jpg", ".svg", ".webp", ".pdf", ".woff", ".woff2", ".ttf"}:
                lines.append(f"- `{item.name}`")
                continue
            summary = doc_comment(item)
            if summary:
                lines.append(f"- `{item.name}` - {summary}")
            elif item.name in {"package.json", "tsconfig.json"}:
                lines.append(f"- `{item.name}` - package/tooling manifest")
            else:
                lines.append(f"- `{item.name}`")

    if not lines:
        lines.append("- _(empty)_")
    return "\n".join(lines)


def render(rel: str, path: Path) -> str:
    kind = classify(rel, path)
    title = rel if rel != "." else "."
    description = describe(rel, path, kind)
    symbols, api_header = public_api(path, kind)
    contents = contents_block(rel, path, kind)
    usage = usage_block(rel, kind, symbols)

    parts = [
        f"# `{title}`",
        "",
        f"> Part of **{PROJECT}** \u2014 {TAGLINE}",
        "",
        description,
        "",
        "## Contents",
        "",
        contents,
        "",
        f"## {api_header}",
        "",
    ]
    if symbols:
        parts.extend(f"- `{sym}`" for sym in symbols)
    elif any(
        f.is_file() and f.suffix in SOURCE_EXT for f in path.iterdir()
    ):
        parts.append(
            "- _(no barrel export - import the individual modules listed in "
            "Contents)_"
        )
    else:
        parts.append("- _(no exported symbols in this directory)_")
    parts += ["", "## Usage", "", usage, "", "---", f"*{GENERATOR_MARKER}*", ""]
    return "\n".join(parts)


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #


def iter_dirs(root: Path):
    for dirpath, dirnames, _ in os.walk(root):
        # Prune in-place so os.walk never descends into dependencies or output.
        dirnames[:] = sorted(d for d in dirnames if d not in EXCLUDE_DIRS)
        current = Path(dirpath)
        rel = current.relative_to(root).as_posix()
        yield rel, current


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report only; exit 1 if incomplete")
    parser.add_argument("--dry-run", action="store_true", help="show planned writes")
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    written = kept = stale = missing = 0
    problems: list[str] = []

    for rel, path in iter_dirs(root):
        readme = path / "README.md"
        if readme.is_file():
            existing = read_text(readme)
            if GENERATOR_MARKER not in existing:
                kept += 1
                print(f"  keep      {rel}/README.md (hand-written)")
                continue
            desired = render(rel, path)
            if desired != existing:
                stale += 1
                if args.check:
                    problems.append(rel)
                print(f"  refresh   {rel}/README.md")
                if not args.check and not args.dry_run:
                    readme.write_text(desired, encoding="utf-8")
            else:
                kept += 1
            continue

        missing += 1
        if args.check:
            problems.append(rel)
        print(f"  create    {rel}/README.md")
        if not args.check and not args.dry_run:
            readme.write_text(render(rel, path), encoding="utf-8")
        written += 1

    print(
        f"\n{written} created, {stale} refreshed, {kept} kept "
        f"({missing} directories were missing documentation)"
    )
    if args.check and problems:
        print(f"\n{len(problems)} directories need documentation.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
