NOTE_CREATED = "note.created"
NOTE_UPDATED = "note.updated"
NOTE_DELETED = "note.deleted"
NOTE_VERSIONED = "note.versioned"
NOTE_COMMENTED = "note.commented"
NOTE_COMMENT_UPDATED = "note.comment.updated"
NOTE_COMMENT_DELETED = "note.comment.deleted"
NOTE_TAGGED = "note.tagged"
NOTE_UNTAGGED = "note.untagged"
NOTE_LINKED = "note.linked"
NOTE_UNLINKED = "note.unlinked"

TASK_CREATED = "task.created"
TASK_UPDATED = "task.updated"
TASK_DELETED = "task.deleted"
TASK_LINKED = "task.linked"
TASK_UNLINKED = "task.unlinked"
TICKET_CREATED = "ticket.created"
TICKET_UPDATED = "ticket.updated"
TICKET_DELETED = "ticket.deleted"
STUDY_ITEM_CREATED = "study_item.created"
STUDY_ITEM_REVIEWED = "study_item.reviewed"

RESOURCE_CREATED = "resource.created"
RESOURCE_UPDATED = "resource.updated"
RESOURCE_DELETED = "resource.deleted"
RESOURCE_RELATED = "resource.related"
RESOURCE_UNRELATED = "resource.unrelated"
ATTACHMENT_CREATED = "attachment.created"
ATTACHMENT_DELETED = "attachment.deleted"
EXTRACTION_COMPLETED = "extraction.completed"

SEARCH_DOCUMENT_INDEXED = "search.document.indexed"
SEARCH_DOCUMENT_REMOVED = "search.document.removed"

AI_PROVIDER_CONFIGURED = "ai.provider.configured"
AI_AGENT_CREATED = "ai.agent.created"
AI_CONVERSATION_CREATED = "ai.conversation.created"
AI_MESSAGE_ADDED = "ai.message.added"
AI_RUN_STARTED = "ai.run.started"
AI_RUN_COMPLETED = "ai.run.completed"
AI_RUN_FAILED = "ai.run.failed"
EMBEDDING_INDEXED = "ai.embedding.indexed"

RSS_FEED_ADDED = "integration.rss.added"
WEBHOOK_CREATED = "integration.webhook.created"
WEBHOOK_DELIVERY_QUEUED = "integration.webhook.delivery.queued"
PLUGIN_INSTALLED = "integration.plugin.installed"
PLUGIN_UNINSTALLED = "integration.plugin.uninstalled"
MCP_SERVER_ADDED = "integration.mcp.added"
SSO_CONNECTION_CONFIGURED = "integration.sso.configured"
SHARE_LINK_CREATED = "integration.share.created"
SHARE_LINK_REVOKED = "integration.share.revoked"

AUDIT_EVENT_RECORDED = "audit.event.recorded"
ANALYTICS_METRIC_RECORDED = "analytics.metric.recorded"
